### ISSUE TITLE
'Inbox' object has no attribute 'find_items'

### ISSUE THREAD

**Issue by nstr10** [ecederstrand/exchangelib#504]
I'm running exchangelib 1.7.3 in production and am trying to update to the latest version. I've run into several breaking changes (shape is now a string, timezone names changed), but the one I can't seem to find a solution to is this when calling `account.inbox.find_items()` with `shape='IdOnly'` and a `datetime_received__range`.

I can provide sample code if necessary but hoping the knowledge that this code works with 1.7.3 might be enough to diagnose my problem.

Thanks for all you do! Exchangelib has done a ton of work for me over the years. :)

**Comment by nstr10** [comment]
Further testing shows that as of 1.9 `datetime_received__range` is an unexpected kwarg.
Intervening versions then show different errors and 1.11.1 is the first version that returns the error in the title of this issue.

**Comment by ecederstrand** [comment]
A lot of things have changed since 1.7.3 and `find_items()` has become a low-level interface. Can you please post the (pseudo)code you are trying to support on newer versions? Unless you are doing something really fancy, there's probably an easy way to rewrite it.

**Comment by nstr10** [comment]
That was easy!

For anyone else stumbling across this, here's some before-and-after code...

Old:
```
from exchangelib import Configuration, Account, Credentials, DELEGATE, folders, EWSTimeZone, EWSDateTime, NTLM, services
from exchangelib.services import IdOnly
from config import mailbox, server, domain, username, password

creds = Credentials(username = "{0}\{1}".format(self.config["domain"], self.config["username"]), password = self.config["password"])
configuration = Configuration(server=server, credentials=creds, auth_type=NTLM)
account = Account(primary_smtp_address=mailbox, config=configuration, access_type=DELEGATE)
start_date, end_date = # boring code removed
items = account.inbox.find_items(datetime_received__range=(start_date_EWS, end_date_EWS), shape=IdOnly)
for item in items:
  contents = account.inbox.fetch(item)
  # Do cool things...
```

New:
```
from exchangelib import Configuration, Account, Credentials, DELEGATE, folders, EWSTimeZone, EWSDateTime, NTLM, services
from config import mailbox, server, domain, username, password

creds = Credentials(username = "{0}\{1}".format(self.config["domain"], self.config["username"]), password = self.config["password"])
configuration = Configuration(server=server, credentials=creds, auth_type=NTLM)
account = Account(primary_smtp_address=mailbox, config=configuration, access_type=DELEGATE)
start_date, end_date = <boring code removed>
items = account.inbox.filter(datetime_received__range=(start_date_EWS, end_date_EWS)).values('id').iterator()
for item in items:
  contents = account.inbox.get(id=item["id"])
  # Do cool things...
```

Note that you can instead do `account.inbox.all()` after filtering, but in my use case I perform additional filtering to ensure each email meets criteria and has not been analyzed previously.

Fetching mail the new way seems to be significantly faster than the old way.

Thanks again, Erik!!!

**Comment by ecederstrand** [comment]
Looks good. You could probably optimize further by fetch multiple emails at a time by ID using the `Account.fetch()` method:

```python
ids_to_fetch = []
for item in items:
    # Do some filtering
    ids_to_fetch.append(item)

full_items = list(account.fetch(ids_to_fetch))
```

Also, if you don't need the contents of every single field on the item, you can use the `only_fields` argument to `Account.fetch()` to limit the amount of data to fetch. Give it a list of field names, e.g. `account.fetch(ids_to_fetch, only_fields=['subject', 'datetime_received'])`
