### ISSUE TITLE
AttributeError: 'datetime.timezone' object has no attribute 'key'

### ISSUE THREAD

**Issue by jrbeilke** [ecederstrand/exchangelib#1014]
**Describe the bug**
Have an app using exchangelib to send emails on a daily schedule that has stopped working recently.

At first the script was failing due to a TypeError for the tzinfo type which was fixed in #1003 but now I'm getting the following AttributeError:
```
  File "/usr/local/lib/python3.6/site-packages/exchangelib/ewsdatetime.py", line 278, in <lambda>
    'pytz_deprecation_shim': lambda z: cls.from_zoneinfo(z.unwrap_shim())
  File "/usr/local/lib/python3.6/site-packages/exchangelib/ewsdatetime.py", line 264, in from_zoneinfo
    return cls(tz.key)
AttributeError: 'datetime.timezone' object has no attribute 'key'
```

Not sure if related, but this does seem similar to the issue reported in #824 

**To Reproduce**
Here's an example of the class we use to send emails via exchangelib: 
```
from exchangelib import DELEGATE, Account, Credentials, Message, Mailbox, Configuration


class ExchangeClient:
    """
    Uses exchange web service to send emails using the exchange server.
    """
    def __init__(self, source, username, password):
        self.source = source
        self.credentials = Credentials(
            username=username,
            password=password
        )

    def send_email(self, destination, subject, message):
        """
        Send an email to the specified destination with the specified subject and message body
        :param destination:
        :param subject:
        :param message:
        :return:
        """
        account = Account(
            primary_smtp_address=self.source,
            credentials=self.credentials,
            autodiscover=True,
            access_type=DELEGATE
        )
        message = Message(
            account=account,
            subject=subject,
            body=message,
            reply_to=["noreply@example.com"],
            to_recipients=[
                Mailbox(email_address=destination)
            ]
        )
        message.send()
```

**Expected behavior**
As far as I can tell this was working with datetime.timezone previously to send emails and this seems to match the docs for sending messages ie.
https://ecederstrand.github.io/exchangelib/#creating-updating-deleting-sending-moving-archiving-marking-as-junk

**Log output**
```
  File "/usr/local/lib/python3.6/site-packages/exchangelib/ewsdatetime.py", line 278, in <lambda>
    'pytz_deprecation_shim': lambda z: cls.from_zoneinfo(z.unwrap_shim())
  File "/usr/local/lib/python3.6/site-packages/exchangelib/ewsdatetime.py", line 264, in from_zoneinfo
    return cls(tz.key)
AttributeError: 'datetime.timezone' object has no attribute 'key'
```

**Additional context**
Python 3.6
exchangelib 4.6.0

**Comment by ecederstrand** [comment]
It seems tzlocal returns a `datetime.timezone` object where we expected a `zoneinfo.Zoneinfo` object.

Which version of tzlocal do you have?

**Comment by jrbeilke** [comment]
This is with tzlocal-4.1

**Comment by ecederstrand** [comment]
Can you check if https://github.com/ecederstrand/exchangelib/commit/936c134c2724b090c63f18f1b3fbee6fae7a2d8b solves this error for you?

**Comment by jrbeilke** [comment]
Yes tested 936c134 and this seems to resolve the issue
